version: "3"
services:
  vault:
    image: vault:1.12.0
    container_name: vault
    command:
      - 'server' 
    environment:
      VAULT_ADDR: "https://vault.example.com:8200"
      VAULT_CACERT: "/vault/userconfig/vault-server-tls/vault-crt.pem"
    networks:
      - devops
    ports:
      - 8200:8200
    volumes:
      - ./certs:/vault/userconfig/vault-server-tls
      - ./config:/vault/config
    cap_add:
      - IPC_LOCK
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: <HOSTNAME>:24224
#        tag: int
  vault-db:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "vault"
      POSTGRES_PASSWORD: "vault123"
      POSTGRES_DB: "vault"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devops
    ports:
      - 5432:5432
networks:
  devops:
volumes:
  pgdata: